
import { AppState, AppPreset } from './types';

export const DEFAULT_STATE: AppState = {
    language: 'zh',
    themeMode: 'dark',
    colorfulThemeBase: 'light',
    colorfulColors: ['#A18CD1', '#FBC2EB', '#8FD3F4'],
    audioFile: null,
    audioUrl: null,
    coverFile: null,
    coverUrl: null,
    backgroundImageFile: null,
    backgroundImageUrl: null,
    backgroundImageScale: 1.05,
    backgroundImageX: 0,
    backgroundImageY: 0,
    srtFile: null,
    lyrics: [],

    // Singer Info Defaults
    singerSrtFile: null,
    singerLyrics: [],
    singerInfoFontSize: 14,
    singerInfoOrientation: 'vertical',
    singerInfoX: 0,
    singerInfoY: 0,
    singerThemeGroups: [
        { typeId: 1, colors: ['#ff9a9e', '#fecfef'] },
        { typeId: 2, colors: ['#a1c4fd', '#c2e9fb'] }
    ],
    showSingerInfo: true,
    forceOverrideSingerTheme: false,
    singerLyricOffset: 0,
    singerLyricGapTolerance: 0.5,

    themeColor: '#d4b996',
    metadata: {
      title: '',
      artist: '',
      album: '',
      visualArtist: '',
      coverSinger: '',
      playerTitle: '',
      playerSubtitle: '',
    },
    lyricFontSizeMain: 32,
    lyricFontSizeSub: 16,
    lyricBold: false, 
    lyricOffset: 0,
    lyricGapTolerance: 0.5,
    lyricActiveColor: null, 
    lyricInactiveColor: null, 
    lyricStrokeWidth: 0,
    lyricStrokeColor: '#000000',
    lyricPrimaryLineIndex: 0, 
    lyricDisplayOrder: [0, 1, 2], 
    
    activeLyricEffect: 'none', 
    activeLyricStreamerColor: '#ffffff',

    trackTitleSize: 48,
    trackTitleColor: null,
    trackTitleBold: true,
    trackTitleItalic: false,

    trackArtistSize: 16,
    trackArtistColor: null,
    trackArtistBold: true,
    trackArtistItalic: false,

    trackAlbumSize: 18,
    trackAlbumColor: null,
    trackAlbumBold: false,
    trackAlbumItalic: true,

    trackVisualArtistSize: 12,
    trackVisualArtistColor: null,
    trackVisualArtistBold: false,
    trackVisualArtistItalic: false,

    trackCoverSingerSize: 12,
    trackCoverSingerColor: null,
    trackCoverSingerBold: false,
    trackCoverSingerItalic: false,

    enableWaves: true, 
    enableParticles: true, 
    enableParticleBeatSync: false,
    particleType: 'circle', 
    particleDirection: 270,
    particleColor: '#ffffff',
    particlePalettes: [['#ffffff']], 
    useThemeColorForParticles: true,
    customParticleFile: null,
    customParticleUrl: null,

    vinylSensitivity: 1.5,
    barSensitivity: 5.0,
    particleSensitivity: 0.5,
    particleSize: 1.0,
    particleBaseSpeed: 0.5,
    contentMaxWidth: 85,
    albumColumnWidth: 35,
    lyricsColumnWidth: 55,
    columnGapWidth: 10,
    albumColumnX: 0,
    albumColumnY: 0,
    albumInfoGap: 40,
    lyricsColumnX: 0,
    lyricsColumnY: 0,
    playerControlsOpacity: 0.5,
    playerBarWidth: 90,
    playerBarHeight: 88,
    playerBarBlur: 16,
    playerBarPositionX: 0,
    playerBarPositionY: 4,
    waveBarScale: 1.0,
    waveBarPositionX: 0,
    waveBarPositionY: 0,
    waveBarBlur: 2,
    waveBarOpacity: 0.4,
    waveBarHeight: 10,
    
    coverArtStyle: 'vinyl',
    enableAlbumProgress: false,
    albumProgressWidth: 4,
    albumProgressOpacity: 0.8,

    vinylStyle: 'classic',
    vinylLabelSize: 42, 
    showVinylCenterDot: true,
    vinylScale: 1.0,
    vinylRotationSpeed: 1.0,

    enableWaterReflection: false,
    lyricEffect: 'glow',

    // Recording Defaults
    recordFormat: 'webm',
    recordBitrate: 12, 
    recordFps: 60,
    recordSampleRate: 48000,
    recordCaptureCursor: false,
    isRecordArmed: false,
    isRecording: false,
};

export const DEFAULT_PRESETS: AppPreset[] = [
    {
        id: 'preset_1080p_16_9',
        name: '1080p 16:9 (Landscape)',
        isDefault: true,
        config: {
            contentMaxWidth: 85,
            albumColumnWidth: 35,
            lyricsColumnWidth: 55,
            columnGapWidth: 10,
            vinylScale: 1.0,
            playerBarWidth: 90,
            playerBarHeight: 88,
            playerBarPositionX: 0,
            playerBarPositionY: 4,
            trackTitleSize: 48,
            trackArtistSize: 16,
            lyricFontSizeMain: 32,
            lyricFontSizeSub: 16,
            albumColumnX: 0,
            albumColumnY: 0,
            albumInfoGap: 40,
            lyricsColumnX: 0,
            lyricsColumnY: 0
        }
    },
    {
        id: 'preset_1080p_9_16',
        name: '1080p 9:16 (Portrait)',
        isDefault: true,
        config: {
            contentMaxWidth: 90,
            albumColumnWidth: 100,
            lyricsColumnWidth: 100,
            columnGapWidth: 5,
            vinylScale: 0.85, 
            playerBarWidth: 95, 
            playerBarHeight: 100,
            playerBarPositionX: 0,
            playerBarPositionY: 2,
            trackTitleSize: 36, 
            trackArtistSize: 14,
            lyricFontSizeMain: 28,
            lyricFontSizeSub: 14,
            albumColumnX: 0,
            albumColumnY: 0,
            albumInfoGap: 30,
            lyricsColumnX: 0,
            lyricsColumnY: 0
        }
    }
];

export const CONFIG_KEYS: (keyof AppState)[] = [
    'language', 'themeMode', 'colorfulThemeBase', 'colorfulColors', 'themeColor', 'metadata',
    'lyricFontSizeMain', 'lyricFontSizeSub', 'lyricBold', 'lyricOffset', 'lyricGapTolerance',
    'lyricActiveColor', 'lyricInactiveColor', 'lyricStrokeWidth', 'lyricStrokeColor',
    'lyricPrimaryLineIndex', 'lyricDisplayOrder', 'activeLyricEffect', 'activeLyricStreamerColor', 
    'trackTitleSize', 'trackTitleColor', 'trackTitleBold', 'trackTitleItalic',
    'trackArtistSize', 'trackArtistColor', 'trackArtistBold', 'trackArtistItalic',
    'trackAlbumSize', 'trackAlbumColor', 'trackAlbumBold', 'trackAlbumItalic',
    'trackVisualArtistSize', 'trackVisualArtistColor', 'trackVisualArtistBold', 'trackVisualArtistItalic',
    'trackCoverSingerSize', 'trackCoverSingerColor', 'trackCoverSingerBold', 'trackCoverSingerItalic',
    'enableWaves', 'enableParticles', 'enableParticleBeatSync',
    'particleType', 'particleDirection', 'particleColor', 'particlePalettes', 'useThemeColorForParticles',
    'vinylSensitivity', 'barSensitivity', 'particleSensitivity', 'particleSize', 'particleBaseSpeed',
    'contentMaxWidth', 'albumColumnWidth', 'lyricsColumnWidth', 'columnGapWidth', 
    'albumColumnX', 'albumColumnY', 'albumInfoGap', 'lyricsColumnX', 'lyricsColumnY',
    'playerControlsOpacity', 'playerBarWidth', 'playerBarHeight', 'playerBarBlur', 'playerBarPositionX', 'playerBarPositionY',
    'waveBarScale', 'waveBarPositionX', 'waveBarPositionY', 'waveBarBlur', 'waveBarOpacity', 'waveBarHeight',
    'coverArtStyle', 'enableAlbumProgress', 'albumProgressWidth', 'albumProgressOpacity',
    'vinylStyle', 'vinylLabelSize', 'showVinylCenterDot', 'vinylScale', 'vinylRotationSpeed',
    'backgroundImageScale', 'backgroundImageX', 'backgroundImageY',
    'enableWaterReflection', 'lyricEffect',
    'recordFormat', 'recordBitrate', 'recordFps', 'recordSampleRate', 'recordCaptureCursor',
    'singerInfoFontSize', 'singerInfoOrientation', 'singerInfoX', 'singerInfoY', 'singerThemeGroups', 'showSingerInfo', 'forceOverrideSingerTheme',
    'singerLyricOffset', 'singerLyricGapTolerance'
];
